name: CI/CD Todolist

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    name: Exécuter les tests Jest sur le Backend
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances et exécuter les tests
        run: |
          cd backend
          npm install
          npm test
  build-and-push-backend:
    name: Construire et Pousser l’image Docker du Backend
    needs: test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Se connecter à Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construire l’image Docker du Backend
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-todolist:latest ./backend

      - name: Pousser l’image du Backend sur Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-todolist:latest
